# Generated by Django 5.2 on 2026-02-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_organizationbranding"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="membership",
            new_name="users_membe_user_id_4e18ad_idx",
            old_name="users_membe_user_id_f11754_idx",
        ),
        migrations.RenameIndex(
            model_name="membership",
            new_name="users_membe_organiz_b81dbf_idx",
            old_name="users_membe_organiz_b7a6a9_idx",
        ),
    ]
