# Generated by Django 5.0.1 on 2026-02-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0004_rename_users_membe_user_id_f11754_idx_users_membe_user_id_4e18ad_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.organization",),
        ),
        migrations.CreateModel(
            name="UserAccessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("TENANT_ADMIN", "Tenant Admin"),
                            ("TENANT_STAFF", "Tenant Staff"),
                        ],
                        db_index=True,
                        default="TENANT_STAFF",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_access_profiles",
                        to="users.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "role"], name="users_usera_tenant__2391bb_idx"
                    ),
                    models.Index(
                        fields=["role", "updated_at"],
                        name="users_usera_role_c5fe9c_idx",
                    ),
                ],
            },
        ),
    ]
