# Generated by Django 5.2 on 2026-07-31 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backfill_tenant_and_access_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN_MANAGER', 'Administrator / Manager'), ('SALES', 'Sales'), ('TECHNICIAN', 'Technician')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invited_memberships', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_memberships', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(db_index=True, max_length=100)),
                ('scope', models.CharField(choices=[('OWN', 'Own records'), ('ASSIGNED', 'Own and assigned records'), ('TENANT_ALL', 'All tenant records')], default='OWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_grants_made', to='users.tenantmembership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='users.tenantmembership')),
            ],
        ),
        migrations.CreateModel(
            name='SupportAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_sessions', to='users.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['actor', 'session_key', 'ended_at'], name='users_suppo_actor_i_15b1f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='users_tenan_user_id_410243_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'base_role', 'is_active'], name='users_tenan_tenant__8838f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_membership'),
        ),
        migrations.AddIndex(
            model_name='tenantpermissiongrant',
            index=models.Index(fields=['membership', 'action_code', 'scope'], name='users_tenan_members_9c0099_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantpermissiongrant',
            constraint=models.UniqueConstraint(fields=('membership', 'action_code'), name='unique_membership_permission_grant'),
        ),
    ]
