# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models

def backfill(apps, schema_editor):
    model = apps.get_model('users', 'OrganizationBranding')
    model.objects.filter(tenant_id__isnull=True).update(tenant_id=models.F('organization_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backfill_tenant_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranding',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_branding', to='users.organization'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
