# Generated by Django 5.2 on 2026-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationbranding',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_branding', to='users.organization'),
        ),
    ]
