# Generated by Django 5.2 on 2026-02-25 09:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        (
            "customers",
            "0009_rename_customers_cu_organiz_652d7c_idx_customers_c_organiz_cb0907_idx_and_more",
        ),
        (
            "users",
            "0004_rename_users_membe_user_id_f11754_idx_users_membe_user_id_4e18ad_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billingdocument",
            name="uniq_payment_reference_per_org",
        ),
        migrations.RenameIndex(
            model_name="billingdocument",
            new_name="billing_bil_organiz_116f6e_idx",
            old_name="billing_doc_org_type_date_idx",
        ),
        migrations.RenameIndex(
            model_name="billingdocument",
            new_name="billing_bil_organiz_a96215_idx",
            old_name="billing_doc_org_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="billinglineitem",
            new_name="billing_bil_organiz_a19b36_idx",
            old_name="billing_item_org_created_idx",
        ),
        migrations.RenameIndex(
            model_name="billinglineitem",
            new_name="billing_bil_organiz_cf8cc8_idx",
            old_name="billing_item_org_doc_idx",
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("18.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="billinglineitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="billinglineitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="billinglineitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment_reference", ""), _negated=True),
                fields=("organization", "payment_reference"),
                name="uniq_payment_reference_per_org",
            ),
        ),
    ]
