# Generated by Django 5.0.1 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0002_remove_billingdocument_uniq_payment_reference_per_org_and_more",
        ),
        ("users", "0005_tenant_useraccessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_billing_documents",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_billing_line_items",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentsequence",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_billing_sequences",
                to="users.organization",
            ),
        ),
    ]
