# Generated by Django 5.0.1 on 2026-02-27 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_billingdocument_tenant_billinglineitem_tenant_and_more"),
        ("customers", "0011_customer_tenant_customerdocument_tenant_and_more"),
        ("products", "0005_product_tenant"),
        ("services", "0006_package_tenant"),
        ("users", "0005_tenant_useraccessprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="billingdocument",
            index=models.Index(
                fields=["tenant", "document_type", "issue_date"],
                name="billing_bil_tenant__133dec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingdocument",
            index=models.Index(
                fields=["tenant", "status", "issue_date"],
                name="billing_bil_tenant__461e47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingdocument",
            index=models.Index(
                fields=["tenant", "payment_reference"],
                name="billing_bil_tenant__7512f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billinglineitem",
            index=models.Index(
                fields=["tenant", "document"], name="billing_bil_tenant__5d3b45_idx"
            ),
        ),
    ]
