# Generated by Django 5.2 on 2026-03-09 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_billingdocument_billing_bil_tenant__133dec_idx_and_more"),
        ("customers", "0012_customer_customers_c_tenant__d5e64f_idx_and_more"),
        ("users", "0006_backfill_tenant_and_access_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdocument",
            name="corrected_invoice",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "invoice"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction_credit_notes",
                to="billing.billingdocument",
            ),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="is_current_version",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="original_invoice",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "invoice"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reissued_versions",
                to="billing.billingdocument",
            ),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="parent_quotation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "quotation"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_quotation_versions",
                to="billing.billingdocument",
            ),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="root_quotation",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "quotation"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_version_history",
                to="billing.billingdocument",
            ),
        ),
        migrations.AddField(
            model_name="billingdocument",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("quotation", "Quotation"),
                    ("invoice", "Invoice"),
                    ("credit_note", "Credit Note"),
                    ("receipt", "Receipt"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billingdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("issued", "Issued"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("reissued", "Reissued"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("quotation", "Quotation"),
                    ("invoice", "Invoice"),
                    ("credit_note", "Credit Note"),
                    ("receipt", "Receipt"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="billingdocument",
            index=models.Index(
                fields=["organization", "root_quotation", "version_number"],
                name="billing_bil_organiz_d6d56d_idx",
            ),
        ),
    ]
