# Generated by Django 5.2 on 2026-03-09 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_billingdocument_corrected_invoice_and_more"),
        ("customers", "0012_customer_customers_c_tenant__d5e64f_idx_and_more"),
        ("users", "0006_backfill_tenant_and_access_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billingdocument",
            name="uniq_billing_number_per_org",
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document_type", "quotation")),
                fields=("organization", "document_type", "number", "version_number"),
                name="uniq_quotation_version_number_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document_type", "quotation"), _negated=True),
                fields=("organization", "document_type", "number"),
                name="uniq_non_quotation_number_per_org",
            ),
        ),
    ]
