# Generated by Django 5.2 on 2026-04-02 00:00

import datetime

from django.db import migrations, models


def backfill_daily_sequence_fields(apps, schema_editor):
    DocumentSequence = apps.get_model("billing", "DocumentSequence")
    BillingDocument = apps.get_model("billing", "BillingDocument")

    for sequence in DocumentSequence.objects.all().iterator():
        sequence.sequence_date = datetime.date(sequence.year, sequence.month, 1)
        next_number = getattr(sequence, "next_number", 1) or 1
        sequence.last_number = max(next_number - 1, 0)
        sequence.save(update_fields=["sequence_date", "last_number"])

    for document in BillingDocument.objects.filter(issued_at__isnull=True).iterator():
        document.issued_at = document.created_at
        document.save(update_fields=["issued_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_remove_billingdocument_uniq_billing_number_per_org_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdocument",
            name="issued_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="documentsequence",
            name="last_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentsequence",
            name="sequence_date",
            field=models.DateField(default=datetime.date(2026, 4, 2)),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_daily_sequence_fields, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="documentsequence",
            name="uniq_billing_sequence_per_org_month",
        ),
        migrations.RemoveField(
            model_name="documentsequence",
            name="month",
        ),
        migrations.RemoveField(
            model_name="documentsequence",
            name="next_number",
        ),
        migrations.RemoveField(
            model_name="documentsequence",
            name="year",
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "document_type", "sequence_date"),
                name="uniq_billing_sequence_per_tenant_day",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(
                fields=["organization", "document_type", "sequence_date"],
                name="billing_doc_organiz_839cf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(
                fields=["tenant", "document_type", "sequence_date"],
                name="billing_doc_tenant__ad3186_idx",
            ),
        ),
    ]
