# Generated by Django 5.2 on 2026-04-13 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone


def backfill_commercial_data(apps, schema_editor):
    BillingLineItem = apps.get_model("billing", "BillingLineItem")
    Customer = apps.get_model("customers", "Customer")
    CustomerSubscription = apps.get_model("billing", "CustomerSubscription")

    BillingLineItem.objects.filter(base_unit_price=Decimal("0.00")).update(
        base_unit_price=models.F("unit_price")
    )

    today = timezone.now().date()
    for customer in Customer.objects.filter(organization__isnull=False).prefetch_related("packages"):
        for package in customer.packages.all():
            if getattr(package, "organization_id", None) != customer.organization_id:
                continue
            CustomerSubscription.objects.get_or_create(
                organization_id=customer.organization_id,
                tenant_id=customer.tenant_id or customer.organization_id,
                customer_id=customer.id,
                package_id=package.id,
                status="active",
                defaults={
                    "start_date": getattr(customer, "created_at", None).date()
                    if getattr(customer, "created_at", None)
                    else today,
                    "billing_day": 1,
                    "monthly_fee_at_signup": package.monthly_fee,
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0007_refactor_document_sequence_to_daily_counters"),
        ("customers", "0013_customer_pricing_tier"),
        ("products", "0006_product_allow_wholesale_product_retail_price_and_more"),
        ("services", "0006_package_tenant"),
        ("users", "0006_backfill_tenant_and_access_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinglineitem",
            name="base_unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="billing_behavior",
            field=models.CharField(
                choices=[
                    ("one_time", "One time"),
                    ("recurring_monthly", "Recurring monthly"),
                ],
                default="one_time",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="discount_reason",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("wholesale", "Wholesale"),
                    ("promotion", "Promotion"),
                    ("manual", "Manual"),
                ],
                default="retail",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("package", "Package"),
                            ("product", "Product"),
                            ("cart", "Cart"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "minimum_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                ("minimum_months", models.PositiveIntegerField(default=1)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage discount"),
                            ("fixed", "Fixed amount discount"),
                            ("free_months", "Free subscription months"),
                            ("wholesale_price", "Wholesale price"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reward_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="users.organization",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="services.package",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_promotions",
                        to="users.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("billing_day", models.PositiveSmallIntegerField(default=1)),
                (
                    "monthly_fee_at_signup",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("paid_through_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_subscriptions",
                        to="users.organization",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="services.package",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_customer_subscriptions",
                        to="users.organization",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="billing.promotion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billinglineitem",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_line_items",
                to="billing.promotion",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("months", models.PositiveIntegerField(default=1)),
                ("free_months", models.PositiveIntegerField(default=0)),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_periods",
                        to="billing.billingdocument",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_periods",
                        to="users.organization",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_periods",
                        to="billing.promotion",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_subscription_periods",
                        to="billing.billingdocument",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="billing.customersubscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_subscription_periods",
                        to="users.organization",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["organization", "is_active", "applies_to"],
                name="billing_pro_organiz_6dd50d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["tenant", "is_active", "applies_to"],
                name="billing_pro_tenant__d9667b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersubscription",
            index=models.Index(
                fields=["organization", "status"], name="billing_cus_organiz_3b5bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersubscription",
            index=models.Index(
                fields=["tenant", "status"], name="billing_cus_tenant__57c898_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersubscription",
            index=models.Index(
                fields=["customer", "status"], name="billing_cus_custome_becdf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersubscription",
            index=models.Index(
                fields=["package", "status"], name="billing_cus_package_99f4ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customersubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("organization", "customer", "package"),
                name="uniq_active_subscription_per_customer_package",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionperiod",
            index=models.Index(
                fields=["organization", "status", "period_start"],
                name="billing_sub_organiz_9dffdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionperiod",
            index=models.Index(
                fields=["tenant", "status", "period_start"],
                name="billing_sub_tenant__1337fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionperiod",
            index=models.Index(
                fields=["invoice"], name="billing_sub_invoice_6f3eac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.UniqueConstraint(
                fields=("subscription", "period_start"),
                name="uniq_subscription_period_start",
            ),
        ),
        migrations.RunPython(backfill_commercial_data, migrations.RunPython.noop),
    ]
