# Generated by Django 5.2 on 2026-06-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_large_list_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customersubscription',
            name='uniq_active_subscription_per_customer_package',
        ),
    ]
