# Generated by Django 5.2 on 2026-06-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_customersubscription_uniq_active_subscription_per_customer_package'),
        ('customers', '0016_customersite'),
        ('services', '0007_package_large_list_indexes'),
        ('users', '0006_backfill_tenant_and_access_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customersite'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['site', 'status'], name='billing_cus_site_id_3289a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization', 'customer', 'site', 'package'), name='uniq_active_subscription_per_customer_site_package'),
        ),
    ]
