# Generated by Django 5.2 on 2026-07-22 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_separate_document_lifecycles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingsheet',
            new_name='billing_bil_organiz_88a46d_idx',
            old_name='billing_billingsheet_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='billingsheet',
            new_name='billing_bil_tenant__447fb2_idx',
            old_name='billing_billingsheet_ten_status_idx',
        ),
        migrations.RenameIndex(
            model_name='billingsheet',
            new_name='billing_bil_organiz_806939_idx',
            old_name='billing_billingsheet_org_cust_idx',
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
