# Generated by Django 5.2 on 2026-07-22

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_rename_billing_billingsheet_org_status_idx_billing_bil_organiz_88a46d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingdocument",
            name="balance_brought_forward",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Outstanding customer balance captured when this invoice was created.",
                max_digits=12,
            ),
        ),
    ]
