# Generated by Django 5.2 on 2026-07-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_billingdocument_balance_brought_forward'),
        ('users', '0007_tenantmembership_tenantpermissiongrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='created_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_billing_documents', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='issued_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_billing_documents', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='last_modified_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_billing_documents', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='payment_recorded_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_recorded_billing_documents', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='responsible_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_billing_documents', to='users.tenantmembership'),
        ),
    ]
