# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_and_validate(apps, schema_editor):
    names = ('BillingDocument', 'BillingLineItem', 'DocumentSequence', 'Promotion', 'CustomerSubscription', 'BillingSheet', 'SubscriptionPeriod')
    for name in names:
        model = apps.get_model('billing', name)
        model.objects.filter(tenant_id__isnull=True).update(tenant_id=models.F('organization_id'))
        if model.objects.filter(tenant_id__isnull=True).exists():
            raise RuntimeError(f'{name} tenant backfill did not complete.')
    BillingItem = apps.get_model('billing', 'BillingItem')
    for item in BillingItem.objects.filter(tenant_id__isnull=True).select_related('billing_sheet'):
        item.tenant_id = item.billing_sheet.tenant_id
        item.save(update_fields=['tenant'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_backfill_document_membership_ownership'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_billing_items', to='users.organization'),
        ),
        migrations.RunPython(backfill_and_validate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='billingdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_billing_documents', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='billinglineitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_billing_line_items', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='billingsheet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_billing_sheets', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_customer_subscriptions', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_billing_sequences', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_promotions', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='subscriptionperiod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscription_periods', to='users.organization'),
        ),
    ]
