# Generated by Django 5.2 on 2026-07-31 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_billingitem_tenant'),
        ('customers', '0018_alter_customer_tenant_alter_customerdocument_tenant_and_more'),
        ('services', '0008_alter_package_tenant'),
        ('users', '0010_alter_organizationbranding_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingdocument',
            name='uniq_payment_reference_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='billingdocument',
            name='uniq_quotation_version_number_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='billingdocument',
            name='uniq_non_quotation_number_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='billingsheet',
            name='uniq_billing_sheet_ref_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='customersubscription',
            name='uniq_active_subscription_per_customer_site_package',
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'quotation')), fields=('tenant', 'document_type', 'number', 'version_number'), name='uniq_quotation_version_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'quotation'), _negated=True), fields=('tenant', 'document_type', 'number'), name='uniq_non_quotation_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='billingdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('tenant', 'payment_reference'), name='uniq_payment_reference_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='billingsheet',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_number'), name='uniq_billing_sheet_ref_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'customer', 'site', 'package'), name='uniq_active_subscription_per_tenant_site_package'),
        ),
    ]
