# Generated by Django 5.2 on 2026-08-07 11:36

from django.db import migrations, models


def backfill_line_units(apps, schema_editor):
    BillingLineItem = apps.get_model('billing', 'BillingLineItem')
    for item in BillingLineItem.objects.select_related('product').all().iterator():
        if item.product_id:
            unit = (item.product.measure_unit or 'Unit').strip() or 'Unit'
        elif item.package_id:
            unit = 'Month' if item.billing_behavior == 'recurring_monthly' else 'Installation'
        else:
            unit = 'Unit'
        item.unit_snapshot = unit
        item.save(update_fields=['unit_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_annual_document_sequences'),
        ('products', '0014_unitofmeasure_product_sales_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglineitem',
            name='unit_snapshot',
            field=models.CharField(default='Unit', help_text='Immutable display unit captured when the document line is saved.', max_length=50),
        ),
        migrations.RunPython(backfill_line_units, migrations.RunPython.noop),
    ]
