# Generated by Django 5.2 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0026_alter_billingdocument_sale_pricing_category'),
        ('customers', '0019_customer_technician_pricing_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocument',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Optional when the whole document concerns one customer site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='customers.customersite'),
        ),
    ]
