# Generated by Django 5.2 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0027_billingdocument_site'),
        ('customers', '0020_internetservice'),
        ('services', '0008_alter_package_tenant'),
        ('users', '0011_cart_financial_control_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglineitem',
            name='internet_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='customers.internetservice'),
        ),
        migrations.AddField(
            model_name='billinglineitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='billing.customersubscription'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='internet_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.internetservice'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('internet_service__isnull', False), ('status', 'active')), fields=('tenant', 'internet_service'), name='uniq_active_subscription_per_internet_service'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='subscription_end_not_before_start'),
        ),
    ]
