# Generated by Django 5.2 on 2026-08-03 07:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0018_alter_customer_tenant_alter_customerdocument_tenant_and_more'),
        ('users', '0010_alter_organizationbranding_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=180)),
                ('client_name', models.CharField(max_length=200)),
                ('service_date', models.DateField(db_index=True)),
                ('work_location', models.CharField(blank=True, default='', max_length=255)),
                ('activity_description', models.TextField()),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Awaiting review'), ('REJECTED', 'Needs correction'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_work_reports', to='users.tenantmembership')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician_work_reports', to='customers.customer')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_work_reports', to='users.organization')),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Draft updated'), ('SUBMITTED', 'Submitted'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CORRECTED', 'Approved report corrected')], db_index=True, max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_report_history_events', to='users.tenantmembership')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='work_reports.technicianworkreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_report_history', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='technicianworkreport',
            index=models.Index(fields=['tenant', 'technician', 'status'], name='work_report_tenant__b38059_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianworkreport',
            index=models.Index(fields=['tenant', 'status', 'submitted_at'], name='work_report_tenant__9ddb08_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianworkreport',
            index=models.Index(fields=['tenant', 'service_date'], name='work_report_tenant__50f386_idx'),
        ),
        migrations.AddIndex(
            model_name='workreporthistory',
            index=models.Index(fields=['tenant', 'report', 'created_at'], name='work_report_tenant__19d038_idx'),
        ),
    ]
