# Generated by Django 5.2 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianworkreport",
            name="client_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
