# Generated by Django 5.2 on 2026-09-01 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cart_financial_control_limits'),
        ('work_reports', '0002_alter_technicianworkreport_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreporthistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Draft updated'), ('SUBMITTED', 'Submitted'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CORRECTED', 'Approved report corrected'), ('PAYMENT_RECORDED', 'Technician payment recorded'), ('PAYMENT_ADJUSTMENT_APPROVED', 'Adjusted payment approved'), ('PAYMENT_CONFIRMED', 'Payment acknowledgement confirmed'), ('PAYMENT_DISPUTED', 'Payment disputed'), ('PAYMENT_VOIDED', 'Payment record voided'), ('PAYMENT_REPLACED', 'Payment record replaced')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='workreporthistory',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='workreporthistory',
            name='to_status',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='TechnicianPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('manager_note', models.TextField(blank=True, default='')),
                ('adjustment_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('AWAITING_CONFIRMATION', 'Awaiting Technician confirmation'), ('CONFIRMED', 'Received confirmed'), ('DISPUTED', 'Disputed'), ('VOIDED', 'Voided')], db_index=True, default='AWAITING_CONFIRMATION', max_length=24)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_payments_recorded', to='users.tenantmembership')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='work_reports.technicianpaymentrecord')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='work_reports.technicianworkreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_payment_records', to='users.organization')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician_payments_voided', to='users.tenantmembership')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'recorded_at'], name='work_report_tenant__9b5669_idx'), models.Index(fields=['tenant', 'report', 'recorded_at'], name='work_report_tenant__2b6e8c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='technician_payment_amount_positive'), models.CheckConstraint(condition=models.Q(('amount_paid', models.F('agreed_amount_snapshot')), models.Q(('adjustment_reason', ''), _negated=True), _connector='OR'), name='technician_payment_adjustment_reason_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='technician_payment_confirmed_at_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'DISPUTED'), _negated=True), models.Q(('disputed_at__isnull', False), models.Q(('dispute_reason', ''), _negated=True)), _connector='OR'), name='technician_payment_dispute_fields_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), _negated=True), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='technician_payment_void_fields_required'), models.UniqueConstraint(condition=models.Q(('status', 'VOIDED'), _negated=True), fields=('report',), name='one_active_technician_payment_per_report')],
            },
        ),
    ]
