# Generated by Django 5.2 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_reports", "0003_alter_workreporthistory_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkReportServiceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(db_index=True)),
                ("activity_note", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_days",
                        to="work_reports.technicianworkreport",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_report_service_days",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["service_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "service_date"],
                        name="wr_day_tenant_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "service_date"),
                        name="unique_work_report_service_date",
                    ),
                ],
            },
        ),
    ]
