# Generated by Django 5.2 on 2026-09-05 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cart_financial_control_limits'),
        ('work_reports', '0005_backfill_workreportservicedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreporthistory',
            name='event',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Draft updated'), ('SUBMITTED', 'Submitted'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('CORRECTED', 'Approved report corrected'), ('PAYMENT_RECORDED', 'Technician payment recorded'), ('PAYMENT_ADJUSTMENT_APPROVED', 'Adjusted payment approved'), ('PAYMENT_CONFIRMED', 'Payment acknowledgement confirmed'), ('PAYMENT_DISPUTED', 'Payment disputed'), ('PAYMENT_VOIDED', 'Payment record voided'), ('PAYMENT_REPLACED', 'Payment record replaced'), ('PAYMENT_BATCH_RECORDED', 'Technician payment batch recorded'), ('PAYMENT_BATCH_CONFIRMED', 'Payment batch confirmed'), ('PAYMENT_BATCH_DISPUTED', 'Payment batch disputed'), ('PAYMENT_BATCH_VOIDED', 'Payment batch voided'), ('PAYMENT_BATCH_REPLACED', 'Payment batch replaced')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TechnicianPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('method_description', models.CharField(blank=True, default='', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('manager_note', models.TextField(blank=True, default='')),
                ('agreed_amount_total_snapshot', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_paid_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('AWAITING_CONFIRMATION', 'Awaiting Technician confirmation'), ('CONFIRMED', 'Received confirmed'), ('DISPUTED', 'Disputed'), ('VOIDED', 'Voided')], db_index=True, default='AWAITING_CONFIRMATION', max_length=24)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_payment_batches_recorded', to='users.tenantmembership')),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='work_reports.technicianpaymentbatch')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_payment_batches', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_payment_batches', to='users.organization')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician_payment_batches_voided', to='users.tenantmembership')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='technicianpaymentrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='work_reports.technicianpaymentbatch'),
        ),
        migrations.AddIndex(
            model_name='technicianpaymentbatch',
            index=models.Index(fields=['tenant', 'technician', 'status'], name='work_report_tenant__48597a_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianpaymentbatch',
            index=models.Index(fields=['tenant', 'status', 'payment_date'], name='work_report_tenant__9e775d_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_amount_total_snapshot__gt', 0)), name='tech_payment_batch_agreed_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid_total__gt', 0)), name='tech_payment_batch_paid_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'OTHER'), _negated=True), models.Q(('method_description', ''), _negated=True), _connector='OR'), name='tech_payment_batch_other_description'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='tech_payment_batch_confirmed_at'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DISPUTED'), _negated=True), models.Q(('disputed_at__isnull', False), models.Q(('dispute_reason', ''), _negated=True)), _connector='OR'), name='tech_payment_batch_dispute_fields'),
        ),
        migrations.AddConstraint(
            model_name='technicianpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), _negated=True), models.Q(('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='tech_payment_batch_void_fields'),
        ),
    ]
