# Generated by Django 5.2 on 2025-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('indoor', 'Indoor Package'), ('outdoor', 'Outdoor Package')], max_length=20)),
                ('speed', models.CharField(max_length=50)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
