# Generated by Django 5.2 on 2025-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package_created_at_package_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
