# Generated by Django 5.2 on 2025-05-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_package_is_active_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
    ]
