# Generated by Django 5.0.1 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_package_org_fk"),
        ("users", "0005_tenant_useraccessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_packages",
                to="users.organization",
            ),
        ),
    ]
