# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    mappings = (
        ('PurchaseLine', 'purchase'), ('CartLine', 'cart'),
        ('InventorySaleLine', 'sale'),
    )
    for model_name, parent_name in mappings:
        model = apps.get_model('inventory', model_name)
        for row in model.objects.filter(tenant_id__isnull=True).select_related(parent_name):
            row.tenant_id = getattr(row, parent_name).tenant_id
            row.save(update_fields=['tenant'])
    Selection = apps.get_model('inventory', 'CartSerialSelection')
    for row in Selection.objects.filter(tenant_id__isnull=True).select_related('cart_line__cart'):
        row.tenant_id = row.cart_line.cart.tenant_id
        row.save(update_fields=['tenant'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_cancelled_status'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_cart_lines', to='users.organization'),
        ),
        migrations.AddField(
            model_name='cartserialselection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_cart_serial_selections', to='users.organization'),
        ),
        migrations.AddField(
            model_name='inventorysaleline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_inventory_sale_lines', to='users.organization'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_purchase_lines', to='users.organization'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
