# Generated by Django 5.2 on 2026-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_cartline_tenant_cartserialselection_tenant_and_more'),
        ('users', '0010_alter_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_cart_lines', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='cartserialselection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_cart_serial_selections', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='inventorysaleline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_inventory_sale_lines', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_purchase_lines', to='users.organization'),
        ),
    ]
