# Generated by Django 5.2 on 2026-09-09 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_cartfinancialapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybalance',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='authoritative_purchase_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='source_purchase_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='source_purchase_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='source_purchase_unit_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventorybalance',
            name='average_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=6, help_text='Positive for stock in; negative for stock out.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=16),
        ),
    ]
