# Generated by Django 5.2 on 2026-07-31 22:19

import django.db.models.deletion
from django.db import migrations, models


def backfill_templates(apps, schema_editor):
    Template = apps.get_model('messaging', 'MessageTemplate')
    Organization = apps.get_model('users', 'Organization')
    tenants = list(Organization.objects.filter(is_active=True).order_by('id'))
    if not tenants:
        default, _ = Organization.objects.get_or_create(
            slug='default-tenant', defaults={'name': 'Default Tenant', 'is_active': True}
        )
        tenants = [default]
    default = next((item for item in tenants if item.slug == 'default-tenant'), tenants[0])
    for template in list(Template.objects.filter(tenant_id__isnull=True).order_by('id')):
        for tenant in tenants:
            if tenant.id == default.id:
                continue
            Template.objects.get_or_create(
                tenant_id=tenant.id, name=template.name,
                defaults={
                    'category': template.category, 'content': template.content,
                    'variables_schema': template.variables_schema,
                    'is_active': template.is_active,
                },
            )
        if Template.objects.filter(tenant_id=default.id, name=template.name, is_active=True).exists():
            template.is_active = False
        template.tenant_id = default.id
        template.save(update_fields=['tenant', 'is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('users', '0010_alter_organizationbranding_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagetemplate',
            name='uniq_active_global_template_name',
        ),
        migrations.RunPython(backfill_templates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='users.organization'),
        ),
    ]
