# Generated by Django 5.2 on 2025-04-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('internet', 'Internet Customer'), ('random', 'Random Customer')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('pending', 'Pending'), ('using', 'Using')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('quotation', 'Customer Quotation'), ('invoice', 'Customer Invoice'), ('receipt', 'Customer Receipt')], max_length=20)),
                ('file', models.FileField(upload_to='customer_documents/')),
                ('date_issued', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InternetCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internet_profile', to='customers.customer')),
            ],
        ),
    ]
