# Generated by Django 5.2 on 2025-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerdocument_notes'),
        ('services', '0004_remove_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='customers', to='services.package'),
        ),
    ]
