# Generated by Django 5.2 on 2025-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetcustomer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internetcustomer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
