# Generated by Django 5.0.1 on 2026-02-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_internetcustomer_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="tin_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="TIN Number"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="vrn_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="VRN Number"
            ),
        ),
    ]
