# Generated by Django 5.2 on 2026-02-21 12:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_address_customer_email_customer_phone_and_more"),
        ("services", "0004_remove_package_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="customerdocument",
            options={
                "ordering": ["-date_issued"],
                "verbose_name": "Customer Document",
                "verbose_name_plural": "Customer Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="internetcustomer",
            options={
                "verbose_name": "Internet Customer Profile",
                "verbose_name_plural": "Internet Customer Profiles",
            },
        ),
        migrations.AddField(
            model_name="customerdocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("internet", "Internet Customer"),
                    ("random", "Random Customer"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="location",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+255123456789'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("blocked", "Blocked"),
                    ("pending", "Pending"),
                    ("using", "Using"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerdocument",
            name="date_issued",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="customerdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("quotation", "Customer Quotation"),
                    ("invoice", "Customer Invoice"),
                    ("receipt", "Customer Receipt"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerdocument",
            name="file",
            field=models.FileField(upload_to="customer_documents/%Y/%m/"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["name", "customer_type"], name="customers_c_name_afb07f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["status", "customer_type"], name="customers_c_status_2dd3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_c_email_4fdeb3_idx"),
        ),
        migrations.AddIndex(
            model_name="customerdocument",
            index=models.Index(
                fields=["customer", "document_type"],
                name="customers_c_custome_a892d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerdocument",
            index=models.Index(
                fields=["date_issued"], name="customers_c_date_is_93e8ba_idx"
            ),
        ),
    ]
