# Generated by Django 5.2 on 2026-02-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_alter_customer_vrn_number"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_c_organiz_cb0907_idx",
            old_name="customers_cu_organiz_652d7c_idx",
        ),
        migrations.RenameIndex(
            model_name="customer",
            new_name="customers_c_organiz_628fa0_idx",
            old_name="customers_cu_organiz_3d07b4_idx",
        ),
        migrations.RenameIndex(
            model_name="customerdocument",
            new_name="customers_c_organiz_06e7cf_idx",
            old_name="customers_cu_organiz_6dc5d3_idx",
        ),
    ]
