# Generated by Django 5.0.1 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0010_customer_soft_delete_and_status"),
        ("users", "0005_tenant_useraccessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_customers",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="customerdocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_customer_documents",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="internetcustomer",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_internet_customers",
                to="users.organization",
            ),
        ),
    ]
