# Generated by Django 5.0.1 on 2026-02-27 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_customer_tenant_customerdocument_tenant_and_more"),
        ("services", "0006_package_tenant"),
        ("users", "0005_tenant_useraccessprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "status"], name="customers_c_tenant__d5e64f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerdocument",
            index=models.Index(
                fields=["tenant", "document_type"],
                name="customers_c_tenant__2b9a5b_idx",
            ),
        ),
    ]
