# Generated by Django 5.2 on 2026-04-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_customer_customers_c_tenant__d5e64f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pricing_tier",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("wholesale", "Wholesale"),
                    ("corporate", "Corporate"),
                    ("vip", "VIP"),
                ],
                db_index=True,
                default="retail",
                max_length=20,
            ),
        ),
    ]
