# Generated by Django 5.2 on 2026-06-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customer_uuid'),
        ('services', '0007_package_large_list_indexes'),
        ('users', '0006_backfill_tenant_and_access_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='customers.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_sites', to='users.organization')),
                ('packages', models.ManyToManyField(blank=True, related_name='customer_sites', to='services.package')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_customer_sites', to='users.organization')),
            ],
            options={
                'verbose_name': 'Customer Site',
                'verbose_name_plural': 'Customer Sites',
                'ordering': ['-is_primary', 'name', 'id'],
                'indexes': [models.Index(fields=['organization', 'customer', 'is_active'], name='customers_c_organiz_f06bcb_idx'), models.Index(fields=['organization', 'customer', 'is_primary'], name='customers_c_organiz_e1caf3_idx'), models.Index(fields=['tenant', 'customer', 'is_active'], name='customers_c_tenant__397c17_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer',), name='uniq_primary_site_per_customer')],
            },
        ),
    ]
