# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_and_validate(apps, schema_editor):
    Organization = apps.get_model('users', 'Organization')
    default = Organization.objects.get(slug='default-tenant')
    Customer = apps.get_model('customers', 'Customer')
    CustomerSite = apps.get_model('customers', 'CustomerSite')
    InternetCustomer = apps.get_model('customers', 'InternetCustomer')
    CustomerDocument = apps.get_model('customers', 'CustomerDocument')
    Customer.objects.filter(tenant_id__isnull=True, organization_id__isnull=False).update(tenant_id=models.F('organization_id'))
    Customer.objects.filter(tenant_id__isnull=True).update(tenant_id=default.id)
    for model in (CustomerSite, CustomerDocument):
        model.objects.filter(tenant_id__isnull=True, organization_id__isnull=False).update(tenant_id=models.F('organization_id'))
        for row in model.objects.filter(tenant_id__isnull=True).select_related('customer'):
            row.tenant_id = row.customer.tenant_id
            row.save(update_fields=['tenant'])
    for row in InternetCustomer.objects.filter(tenant_id__isnull=True).select_related('customer'):
        row.tenant_id = row.customer.tenant_id
        row.save(update_fields=['tenant'])
    if any(model.objects.filter(tenant_id__isnull=True).exists() for model in (Customer, CustomerSite, InternetCustomer, CustomerDocument)):
        raise RuntimeError('Customer tenant backfill did not complete.')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_backfill_customer_sites'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill_and_validate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_customers', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_customer_documents', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='customersite',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_customer_sites', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='internetcustomer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_internet_customers', to='users.organization'),
        ),
    ]
