# Generated by Django 5.2 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0019_customer_technician_pricing_tier'),
        ('users', '0011_cart_financial_control_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=64)),
                ('name', models.CharField(default='Primary Internet Service', max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('operational_status', models.CharField(choices=[('unknown', 'Status unknown'), ('active', 'Active'), ('blocked', 'Blocked'), ('disconnected', 'Disconnected')], db_index=True, default='unknown', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='users.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internet_services', to='customers.customersite')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_internet_services', to='users.organization')),
            ],
            options={
                'ordering': ['site_id', 'service_code', 'id'],
                'indexes': [
                    models.Index(fields=['tenant', 'customer', 'operational_status'], name='cust_is_t_cust_stat_idx'),
                    models.Index(fields=['tenant', 'site', 'operational_status'], name='cust_is_t_site_stat_idx'),
                    models.Index(fields=['tenant', 'ip_address'], name='cust_is_t_ip_idx'),
                    models.Index(fields=['tenant', 'vlan_id'], name='cust_is_t_vlan_idx'),
                ],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'service_code'), name='uniq_internet_service_code_per_tenant')],
            },
        ),
    ]
