# Generated by Django 5.2 on 2026-02-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_organiz_01c53f_idx",
            old_name="audit_auditl_organiza_2d54de_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_organiz_cdea29_idx",
            old_name="audit_auditl_organiza_f0cb5b_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_organiz_3ea24d_idx",
            old_name="audit_auditl_organiza_3be45f_idx",
        ),
    ]
