# Generated by Django 5.0.1 on 2026-02-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audit",
            "0002_rename_audit_auditl_organiza_2d54de_idx_audit_audit_organiz_01c53f_idx_and_more",
        ),
        ("users", "0005_tenant_useraccessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_audit_logs",
                to="users.organization",
            ),
        ),
    ]
