# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models

def backfill(apps, schema_editor):
    model = apps.get_model('audit', 'AuditLog')
    model.objects.filter(tenant_id__isnull=True).update(tenant_id=models.F('organization_id'))
    if model.objects.filter(tenant_id__isnull=True).exists():
        raise RuntimeError('Audit tenant backfill did not complete.')


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_action_type_auditlog_document_id_and_more'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_audit_logs', to='users.organization'),
        ),
    ]
