# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models

def backfill(apps, schema_editor):
    model = apps.get_model('integrations', 'IntegrationConsumer')
    model.objects.filter(tenant_id__isnull=True).update(tenant_id=models.F('organization_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconsumer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_integration_consumers', to='users.organization'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
