# Generated by Django 5.2 on 2026-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationconsumer_tenant'),
        ('users', '0010_alter_organizationbranding_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconsumer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_integration_consumers', to='users.organization'),
        ),
    ]
