# Generated by Django 5.2 on 2026-07-06 12:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_backfill_tenant_and_access_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('customer', 'Customer'), ('product', 'Product'), ('package', 'Package'), ('supplier', 'Supplier')], db_index=True, max_length=50)),
                ('key', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Use a lowercase key with letters, numbers, and underscores only.', regex='^[a-z][a-z0-9_]*$')])),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice')], db_index=True, max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('default_value', models.TextField(blank=True, default='')),
                ('choices', models.TextField(blank=True, default='', help_text='One choice per line. Used only for choice fields.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_on_create', models.BooleanField(default=True)),
                ('show_on_edit', models.BooleanField(default=True)),
                ('show_on_detail', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_field_definitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_field_definitions', to='users.organization')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_custom_field_definitions', to='users.organization')),
            ],
            options={
                'ordering': ['target_model', 'display_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='custom_fields.customfielddefinition')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_field_values', to='users.organization')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_custom_field_values', to='users.organization')),
            ],
            options={
                'ordering': ['field_definition__display_order', 'field_definition__label', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['organization', 'target_model', 'is_active'], name='cf_def_org_target_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['organization', 'target_model', 'display_order'], name='cf_def_org_target_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'target_model', 'key'), name='uniq_custom_field_key_per_target'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['organization', 'target_model', 'object_id'], name='cf_value_org_target_object_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['organization', 'field_definition'], name='cf_value_org_definition_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('field_definition', 'target_model', 'object_id'), name='uniq_custom_field_value_per_object'),
        ),
    ]
