# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models

def backfill(apps, schema_editor):
    for name in ('CustomFieldDefinition', 'CustomFieldValue'):
        model = apps.get_model('custom_fields', name)
        model.objects.filter(tenant_id__isnull=True, organization_id__isnull=False).update(tenant_id=models.F('organization_id'))
        if model.objects.filter(tenant_id__isnull=True).exists():
            raise RuntimeError(f'{name} tenant backfill did not complete.')


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_custom_field_definitions', to='users.organization'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_custom_field_values', to='users.organization'),
        ),
    ]
