# Generated by Django 5.2 on 2026-07-31 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0002_alter_customfielddefinition_tenant_and_more'),
        ('users', '0010_alter_organizationbranding_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customfielddefinition',
            name='uniq_custom_field_key_per_target',
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'target_model', 'key'), name='uniq_custom_field_key_per_tenant_target'),
        ),
    ]
