# Generated by Django 5.2 on 2026-04-13 08:59

from django.db import migrations, models


def backfill_retail_price(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(retail_price__isnull=True).update(retail_price=models.F("selling_price"))


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_wholesale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_min_quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.RunPython(backfill_retail_price, migrations.RunPython.noop),
    ]
