# Generated by Django 5.2 on 2026-07-31

from collections import Counter

from django.db import migrations, models


def backfill_category_measure_units(apps, schema_editor):
    ProductCategory = apps.get_model('products', 'ProductCategory')
    Product = apps.get_model('products', 'Product')

    for category in ProductCategory.objects.all().iterator():
        units = Counter(
            value.strip()
            for value in Product.objects.filter(catalog_category_id=category.pk).values_list('measure_unit', flat=True)
            if value and value.strip()
        )
        category.measure_unit = units.most_common(1)[0][0] if units else 'Unit'
        category.save(update_fields=['measure_unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_backfill_inventory_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(
                choices=[
                    ('layers', 'General catalog'),
                    ('camera', 'Camera & security'),
                    ('tools', 'Installation & tools'),
                    ('laptop', 'Computing'),
                    ('router', 'Networking'),
                    ('switch', 'Network switching'),
                    ('cable', 'Cables & accessories'),
                ],
                default='layers',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='measure_unit',
            field=models.CharField(
                default='Unit',
                help_text='Default unit for new products assigned to this category, for example Unit, Pc, Meter, Kg, or Box.',
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill_category_measure_units, migrations.RunPython.noop),
    ]
