# Generated by Django 5.2 on 2026-07-31 22:16

import django.db.models.deletion
from django.db import migrations, models

def backfill(apps, schema_editor):
    model = apps.get_model('products', 'Product')
    model.objects.filter(tenant_id__isnull=True).update(tenant_id=models.F('organization_id'))
    if model.objects.filter(tenant_id__isnull=True).exists():
        raise RuntimeError('Product tenant backfill did not complete.')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_backfill_product_category_icons'),
        ('users', '0009_organizationbranding_tenant'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_products', to='users.organization'),
        ),
    ]
