# Generated by Django 5.2 on 2026-08-07 11:36

import django.db.models.deletion
from django.db import migrations, models


def backfill_units(apps, schema_editor):
    Unit = apps.get_model('products', 'UnitOfMeasure')
    Category = apps.get_model('products', 'ProductCategory')
    Product = apps.get_model('products', 'Product')

    unit_cache = {}
    through_model = Category.allowed_units.through

    def add_allowed(category_id, unit_id):
        if not through_model.objects.filter(productcategory_id=category_id, unitofmeasure_id=unit_id).exists():
            through_model.objects.create(productcategory_id=category_id, unitofmeasure_id=unit_id)

    def unit_for(tenant_id, raw_name):
        name = (raw_name or 'Unit').strip() or 'Unit'
        key = (tenant_id, name.casefold())
        if key not in unit_cache:
            unit, _ = Unit.objects.get_or_create(
                tenant_id=tenant_id,
                name=name,
                defaults={'organization_id': tenant_id, 'symbol': ''},
            )
            unit_cache[key] = unit
        return unit_cache[key]

    for category in Category.objects.all().iterator():
        default_unit = unit_for(category.tenant_id, category.measure_unit)
        category.default_unit_id = default_unit.pk
        category.save(update_fields=['default_unit'])
        add_allowed(category.pk, default_unit.pk)

    for product in Product.objects.all().iterator():
        sales_unit = unit_for(product.tenant_id, product.measure_unit)
        product.sales_unit_id = sales_unit.pk
        product.save(update_fields=['sales_unit'])
        if product.catalog_category_id:
            add_allowed(product.catalog_category_id, sales_unit.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_technician_price'),
        ('users', '0010_alter_organizationbranding_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units_of_measure', to='users.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_units_of_measure', to='users.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sales_unit',
            field=models.ForeignKey(blank=True, help_text='Unit shown on quotations and invoices for this product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='allowed_units',
            field=models.ManyToManyField(blank=True, help_text='Units that products in this category may use for sales.', related_name='product_categories', to='products.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='Preselected sales unit for new products in this category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_product_categories', to='products.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='products_un_tenant__0ba5a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_uom_tenant_name'),
        ),
        migrations.RunPython(backfill_units, migrations.RunPython.noop),
    ]
