# Generated by Django 5.2 on 2026-09-09 08:19

from decimal import Decimal
from django.db import migrations, models


def backfill_purchase_defaults(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all().iterator():
        label = product.measure_unit or 'Unit'
        if product.sales_unit_id:
            unit = product.sales_unit
            label = unit.symbol or unit.name
        Product.objects.filter(pk=product.pk).update(
            default_purchase_unit_label=label,
            default_purchase_conversion_factor=Decimal('1.000000'),
            default_purchase_unit_cost=product.buying_price,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_purchase_conversion_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Number of base stock units in one purchase pack.', max_digits=16),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of one default purchase pack.', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(backfill_purchase_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=6, help_text='Normalized acquisition cost per base stock/sales unit.', max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
